version: '3.7'
services:
  nginx:
    image: 'arm64v8/nginx:stable-alpine'
    container_name: elteam_nginx
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs:/var/log/nginx
    networks:
      - elteam_network

  db:
    image: 'arm64v8/mysql:latest'
    container_name: elteam_db
    ports:
      - '3336:3306'
    environment:
      MYSQL_DATABASE: elteam
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - elteam_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elteam_app
    volumes:
      - ./:/var/www/html
    networks:
      - elteam_network

  redis:
    image: 'arm64v8/redis:alpine'
    container_name: elteam_redis
    networks:
      - elteam_network

  rabbitmq:
    hostname: 'elteam-rabbitmq'
    image: 'arm64v8/rabbitmq:3-management-alpine'
    container_name: rabbitmq
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - ./docker/rabbitmq/data/:/var/lib/rabbitmq/
    networks:
      - elteam_network

#Volumes
volumes:
  dbdata:

networks:
  elteam_network:
    driver: bridge
