version: '3.7'
services:
  nginx:
    image: 'nginx:stable-alpine'
    container_name: elteam_nginx
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs:/var/log/nginx

  db:
    image: mysql:latest
    container_name: elteam_db
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: elteam
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elteam_app
    volumes:
      - ./:/var/www/html

  redis:
    image: redis:alpine
    container_name: elteam_redis

#Volumes
volumes:
  dbdata:
